# Generated by Django 3.1.4 on 2021-02-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('c_email', models.CharField(default='', max_length=70)),
                ('c_phone', models.CharField(default='', max_length=70)),
                ('c_desc', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('pin_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(default='', max_length=50)),
                ('prod_price', models.FloatField(default=0.0)),
                ('prod_brand', models.TextField()),
                ('prod_quantity', models.IntegerField(default=0)),
                ('prod_desc', models.CharField(default='', max_length=3000)),
                ('prod_image', models.ImageField(upload_to='shop/images')),
            ],
        ),
    ]
