# Generated by Django 3.1.4 on 2021-02-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210213_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_brand',
            field=models.CharField(default='', max_length=50),
        ),
    ]
